- name: Include variables
  include_vars:
    file: ../../vars.yml

- name: Download Logstash Deb Package
  get_url:
    url: '{{ logstash_download_url }}{{ logstash_version }}-amd64.deb'
    dest: /tmp

- name: Install Logstash Deb Package
  become: yes
  apt:
    deb: /tmp/{{ logstash_version }}-amd64.deb

- name: Copy Logstash Config to Remote Servers 
  become: yes
  copy:
    src: ./logstash/logstash.yml
    dest: '{{ logstash_yaml }}'
    backup: yes

- name: Copy Logstash Pipline Config to Remote Servers 
  become: yes
  copy:
    src: ./logstash/pipelines.yml
    dest: '{{ pipelines_yaml }}'
    backup: yes

- name: Copy Logstash conf.d to Remote Servers 
  become: yes
  copy:
    src: ./logstash/conf.d
    dest: '{{ logstash_config_path }}'
    backup: yes

- name: Start Logstash Service
  become: yes
  service:
    name: logstash
    state: started
    enabled: yes