- hosts: logstash_server
  gather_facts: yes
  tasks:
    - name: Copy Logstash Pipline Config to Remote Servers 
      become: yes
      copy:
        src: ./logstash/pipelines.yml
        dest: /etc/logstash/pipelines.yml

    - name: Copy Logstash conf.d to Remote Servers 
      become: yes
      copy:
        src: ./logstash/conf.d
        dest: /etc/logstash
    
    - name: Start Logstash Service
      become: yes
      service:
        name: logstash
        state: started
        enabled: yes