- hosts: es1
  gather_facts: yes
  tasks:
    - name: Config Elasticsearch Builtin Password
      become: yes
      expect:
        command: /usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive
        responses:
          'Please confirm that you would like to continue [y/N]': 'y'
          # 'Enter password for [elastic]:': 'changeme'
          'nter password for': 'R5b6WyRp'
        echo: yes

    - name: Gen SSL CA
      become: yes
      expect:
        command: /usr/share/elasticsearch/bin/elasticsearch-certutil ca
        responses:
          'Please enter the desired output file [elastic-stack-ca.p12]:': ''
          'Enter password for elastic-stack-ca.p12': 'R5b6WyRp'
        echo: yes
    
    - name: Gen SSL Node Certificate
      become: yes
      expect:
        command: /usr/share/elasticsearch/bin/elasticsearch-certutil cert --ca elastic-stack-ca.p12
        responses:
          'Enter password for CA': 'R5b6WyRp'
          'Please enter the desired output file [elastic-certificates.p12]:': ''
          'Enter password for elastic-certificates.p12:': 'R5b6WyRp'
        echo: yes

