- hosts: all
  gather_facts: yes

  pre_tasks:
    - name: update apt cache if needed
      become: yes
      apt:
        update_cache=yes
        cache_valid_time=3600
    - name: Include variables
      include_vars:
        file: vars.yml

  # tasks:
  #   - name: Install Java Runtime Environment 
  #     become: yes
  #     apt:
  #       name: default-jre
  #       state: present

- hosts: elasticsearch_server
  gather_facts: no
  roles:
    - elasticsearch

- hosts: kibana_server
  gather_facts: no
  roles:
    - kibana

- hosts: logstash_server
  gather_facts: no
  roles:
    - logstash