- name: Download Kibana Deb Package
  get_url:
    url: '{{ kibana_download_url }}{{ kibana_version }}-amd64.deb'
    dest: /tmp

- name: Install Kibana Deb Package
  become: yes
  apt:
    deb: /tmp/{{ kibana_version }}-amd64.deb

- name: Copy Kibana Config to Remote Servers 
  become: yes
  template:
    src: ../../templates/kibana.yml
    dest: "{{ kibana_yaml }}"

- name: Start Kibana Service
  become: yes
  service:
    name: kibana
    state: started
    enabled: yes