filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml

filebeat.inputs:
- type: log
  paths:
    - /var/log/radius/radacct/*/auth-detail-202107.*
  tags: ["auth"]
  multiline.type: pattern
  multiline.pattern: '^[[:space:]]'
  multiline.negate: false
  multiline.match: after

  exclude_files: ['.gz$']

output.logstash:
  hosts: ["10.252.93.185:5044"]