- name: Download Elastic Deb Package
  get_url:
    url: '{{ elasticsearch_download_url }}{{ elasticsearch_version }}-amd64.deb'
    dest: /tmp

- name: Install Elastic Deb Package
  become: yes
  apt:
    deb: /tmp/{{ elasticsearch_version }}-amd64.deb

- name: Copy Elasticsearch Config to Remote Servers 
  become: yes
  template:
    src: ../../templates/elasticsearch.yml
    dest: "{{ elasticsearch_yaml }}"

- name: Start ElasticSearch Service
  become: yes
  service:
    name: elasticsearch
    state: started