- name: Include variables
  include_vars:
    file: ../../vars.yml

- name: Download Elastic Deb Package
  get_url:
    url: '{{ elasticsearch_download_url }}{{ elasticsearch_version }}-amd64.deb'
    dest: /tmp

- name: Install Elastic Deb Package
  become: yes
  apt:
    deb: /tmp/{{ elasticsearch_version }}-amd64.deb

- name: Copy Elastic Config to Remote Servers 
  become: yes
  copy:
    src: ./elasticsearch/elasticsearch.yml
    dest: '{{ elasticsearch_yaml }}'
    backup: yes

- name: Updating Elastic Config (Node Name)
  become: yes
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'node.name:'
    line: 'node.name: {{ inventory_hostname }}'

- name: Update Elastic Config (IP Address)
  become: yes
  lineinfile:
    destfile: '{{ elasticsearch_yaml }}'
    regexp: 'network.host'
    line: 'network.host: {{ network_host }}'

- name: Start ElasticSearch Service
  become: yes
  service:
    name: elasticsearch
    state: started